---
- name: DEPLOY APP IN NEW NAMESPACE
  hosts: localhost
  tasks:
    - name: Create a k8s namespace
      kubernetes.core.k8s:
        name: fargate
        api_version: v1
        kind: Namespace
        state: present
    - name: Deploy nginx app
      kubernetes.core.k8s:
        src: /Users/utkalnayak/code/ansible/learn-ansible/nginx-eks-fargate.yaml
        state: present
        namespace: fargate
