---
- name: INSTALL JAVA AND NET-TOOLS
  hosts: droplet
  tasks:
    - name: update apt
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
    - name: install java 8
      apt:
        name: openjdk-8-jre-headless
    - name: Install net-tools
      apt:
        name: net-tools

- name: DOWNLOAD AND UNPACK NEXUS INSTALLER
  hosts: droplet
  tasks:
    - name: Check if folder exists
      stat:
        path: /opt/nexus
      register: check_folder_result
    - name: Download Nexus
      get_url:
        url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
        dest: /opt
      register: nexus_download_result
    - name: Untar Nexus installer
      unarchive:
        src: "{{nexus_download_result.dest}}"
        dest: /opt
        remote_src: true
      when: not check_folder_result.stat.exists
    - name: Find Nexus Folder name
      find:
        paths: /opt
        pattern: "nexus-*"
        file_type: directory
      register: find_folder_name_result
    - name: Rename folder name of Nexus
      shell: mv {{find_folder_name_result.files[0].path}} /opt/nexus
      when: not check_folder_result.stat.exists

- name: CREATE NEXUS USER TO OWN NEXUS FOLDER
  hosts: droplet
  tasks:
    - name: Create group for Nexus user
      group:
        name: nexus
        state: present
    - name: Create nexus user
      user:
        name: nexus
        group: nexus
    - name: Make nexus user owner of nexus folder
      file:
        path: /opt/nexus
        state: directory
        owner: nexus
        group: nexus
        recurse: yes
    - name: Make nexus user owner of sonatype folders
      file:
        path: /opt/sonatype-work
        state: directory
        owner: nexus
        group: nexus
        recurse: yes

- name: START NEXUS WITH NEXUS USER
  hosts: droplet
  become: True
  become_user: nexus
  tasks:
    - name: Add Nexus user to nexus config
      lineinfile:
        path: /opt/nexus/bin/nexus.rc
        regex: '^#run_as_user=""'
        line: run_as_user="nexus"
    - name: Start Nexus instance
      command: /opt/nexus/bin/nexus start
    - name: Wait (Pause) for 30 seconds
      pause:
        seconds: 30
    - name: Report Nexus Process
      command: netstat -plnt
      register: nexus_instance_status
    - debug:
        msg: "{{ nexus_instance_status.stdout_lines}}"
